spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/farmacia_pos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: testSecretKeyForJWTThatIsLongEnoughToBeSecure1234567890
  expiration: 28800000

logging:
  level:
    com.tecnoa.pos: DEBUG
    org.hibernate.SQL: DEBUG
